version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "vitest"
          - "@vitejs/*"
          - "vite"
      toolchain:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "vitest"
          - "@vitejs/*"
          - "vite"
